### ISSUE TITLE
ability to install from URL ?

### ISSUE THREAD

**Issue by tyoung13** [andskli/puppet-netbackup#13]
Hello !    Any plans in the works for the NetBackup module for Puppet to be able to install NBU client software RPMs from URLs ?

**Comment by andskli** [comment]
The decision was to not install from RPMs since RPMs was not officially supplied by Veritas (Symantec at the time) back when this was initially released. If that has changed, supporting RPM based installations would make sense. But for now I will close this issue since I can't find anything regarding support of RPM based installations from Veritas.

**Comment by tyoung13** [comment]
Thanks for the reply !  Actually, as of the 7.7.3 NBU tree, installation from RPMs is indeed supported now.  

https://www.veritas.com/content/support/en_US/doc/ka6j0000000LA1WAAW     (PDF page 106, "Install and upgrade of the Linux client binaries with standard RPM tools")

**Comment by andskli** [comment]
@tyoung13 thanks for the update on that. I do not have access to NBU since I no longer work actively with the product. That said, I'd be happy to review a pull request that adds support for it. It shouldn't be much work to get it in place tbh.

**Comment by tyoung13** [comment]
thanks!   Let me know if you need me to do any testing.  Also, that said, I sort of thing we'll do most of our NBU-related activity via Bolt rather than Puppet Forge plug-ins.
 

    On Monday, April 2, 2018 10:03 AM, Andreas Skarmutsos Lindh <notifications@github.com> wrote:
 

 @tyoung13 thanks for the update on that. I do not have access to NBU since I no longer work actively with the product. That said, I'd be happy to review a pull request that adds support for it. It shouldn't be much work to get it in place tbh.—
