### ISSUE TITLE
PuppetForge Not maintained

### ISSUE THREAD

**Issue by stivesso** [andskli/puppet-netbackup#2]
Hi,

I'd just like to know whether or not this module is still supported on the Forge, I've tried initially to install the forge version but that wasn't working (I had to switch the the github version).

**Comment by andskli** [comment]
I've been lousy at maintaining this module since I'm no longer an active NBU user. I'm currently on vacation but try to go over and see what's what when I get back.

**Comment by stivesso** [comment]
Hello, If you don't mind, I'm suggesting to take over the PuppetForge Module update (as I'm still actively using Netbackup product and planning to enhance the module with full Solaris 10/11 Support and enhanced documentation).

**Comment by andskli** [comment]
@stivesso thanks for the feedback. I have updated the release with your changes and re-published the module (I changed username on puppet forge with seems to leave me with no other option than to republish under my new username, strange enough). It's available at https://forge.puppet.com/andskli/netbackup.

I do plan to maintain this repo and get better at responding to issues and pull requests.

**Comment by andskli** [comment]
@stivesso I also added you as a collaborator on this repository!

**Comment by stivesso** [comment]
@andskli , Thanks for that. I'm delighted to be part of this project!
