### ISSUE TITLE
Ensure that netbackup service is restarted after config file is changed 

### ISSUE THREAD

**Issue by SohamChakraborty** [andskli/puppet-netbackup#9]
After modification of bp.conf, we should restart the netbackupu service. This issue is to track the addition of that functionality. 

This is an off-shoot of https://github.com/andskli/puppet-netbackup/issues/8#issuecomment-310663234

**Comment by SohamChakraborty** [comment]
I asked my colleague to take a look into this and there is a PR now. Tests have passed in travis. Let me or him know if there is any issues with the PR.

Cheers!

**Comment by stivesso** [comment]
Thanks for that Soham,

I've commented on the PR now (proposing a slightly different approach), please let me know what you think about that proposition.

Best Regards.
